[Sonar]
interval_ms = 50
std = 0.01
normal_std = 0.56
constant_std = 0.1

[MCPositionEstimator]
localisation = "continuous"
start_x = 0.0
start_y = 0.0
start_theta = 0.0

num_particles = 100

[Geofence]
points_x = [0.0, 2.0, 2.0, 0.0, 0.0]
points_y = [0.0, 0.0, 2.0, 2.0, 0.0]

[Navigator]
waypoints_x = [0.2, 0.2, 0.4]
waypoints_y = [0.2, 0.4, 0.4]
waypoint_threshold = 0.05
interval_ms = 100

[MotorController]
interval_ms  = 50
wheel_radius = 0.0265
wheel_base   = 0.212

turn_encoder_a = 1.0
turn_encoder_b = 1.30

move_encoder_a = 1.0
move_encoder_b = 0.98

encoder_cpr = 360

left_motor  = "port_D"
right_motor = "port_C"

max_power = 70.0
max_dps   = 360.0