virtual = true

# Command list
[[commands]]
type = "FORWARDS"
distance = 1.0
power = 0.5

# [[commands]]
# type = "TURN"
# angle = 90
# power = 0.5

[robot]
    # Wheel base in metres measured from the outside of each wheel 
    outer_wheel_base = 0.25

    # Wheel base in metres measured from the inside of each wheel 
    inner_wheel_base = 0.2

    # Wheel radius in metres
    wheel_radius = 0.05

    # Default terrain configuration
    default_terrain = "carpet"

    # Heading differential (+ve for clockwise offset)
    heading_diff = 0.0

    # Weight in kg
    weight = 1

    # Motor port configuration
    left_motor = 'PORT_A'
    right_motor = 'PORT_D'

    # Robot configuration (enumeration) possible values :
    # tandem (2 wheel differential drive - like a roomba)
    configuration = "tandem"

    [robot.configs]
        [robot.configs.carpet]
            wheel_slip_acc = 0
            wheel_slip_vel = 0
        [robot.configs.table]
            wheel_slip_acc = 0
            wheel_slip_vel = 0